import { cn } from "@/lib/utils";
import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";
import { Toaster } from "@/components/ui/sonner";
import ProvidersWrapper from "@/providers/provider-wrapper";

const poppins = Poppins({
  variable: "--font-poppins",
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={cn(
          "antialiased border-border outline-ring/50 bg-background text-foreground scrollbar-none",
          poppins.className
        )}
      >
        <ProvidersWrapper>{children}</ProvidersWrapper>
        <Toaster />
      </body>
    </html>
  );
}
